name: CI

on:
  push:
    branches:
      - master
      - "hotfix/*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Build Assets
        run: npm i && npm run build

      - name: Build Site
        uses: JekyllNet/action@main
        with:
          source: .
          destination: _site
