name: CI

on:
  push:
    branches:
      - master
      - "hotfix/*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Build Assets
        run: npm i && npm run build

      - name: Build Site
        uses: JekyllNet/action@v1
        with:
          source: .
          destination: _site

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - name: Install html-proofer
        run: gem install html-proofer -v "~> 5.0"

      - name: Test Site
        run: |
          htmlproofer _site \
            --disable-external \
            --ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"
